### ISSUE TITLE
Vulkan memory allocator (VMA) support?

### ISSUE THREAD

**Issue by elviras9t** [WolfSource/Wolf.Engine#17]
Hey, I have some questions. Why Wolf.Engine does not using VMA (Vulkan Memory Allocator)? Or you have so good memory allocator?

**Comment by PooyaEimandar** [comment]
neither good nor bad. :)
But I'm going to integrate it with AMD's VulkanMemoryAllocator in the next release.

**Comment by PooyaEimandar** [comment]
@elviras9t 
w_buffer integrated with AMD's VulkanMemoryAllocator 
[#76f3743](https://github.com/WolfSource/Wolf.Engine/commit/76f3743300854e6d28b64ce4260f51c0ae606a56)
