### ISSUE TITLE
Issue with AVX2 flag & masked occlusion culling

### ISSUE THREAD

**Issue by Hasselgren** [WolfSource/Wolf.Engine#9]
Hi Pooya,

Glad you managed to solve the coordinate system issue with the occlusion culling library. 

I took a quick peak at your latest commit and just wanted to mention an issue with the project configuration so it doesn't come back and haunt you later. Basically, you want to set the project default instruction set to your lowest target platform (for example SSE2) and then manually change **only** the MaskedOcclusionCullingAVX2.cpp file to compile with AVX2. 

The reason for this is pretty contrived, and has to do with the new VEX instruction encoding for SSE instructions (https://software.intel.com/en-us/articles/avoiding-avx-sse-transition-penalties) which gives best performance when mixing AVX2 and SSE. As you've configured the project now, the SSE fallback in MaskedOcclusionCulling.cpp will also use the VEX encoding, and ironically this will cause it to crash on SSE machines. This wasn't documented in the library, so I've asked to add an extra #error pragma and some comments to ensure that the project is correctly configured.

Happy coding,
/Jon

**Comment by PooyaEimandar** [comment]
Hi Jon
Thanks for the guide. Actually the CPU of my home PC is pretty old ( AMD  Phenom II X4 :) ) and does not support AVX2, so when I'm coding in my home I need to change configuration to SSE, sure I won't ship the engine with this configuration.
Thank you again.

Kind Regards
Pooya
